export const string = {
  fun: 'Fun',
  car: 'Car',
  rate: 'Rate',
  skip: 'skip',
  food: 'Food',
  gift: 'Gift',
  home: 'Home',
  sale: 'Sale',
  book: 'Book',
  fruit: 'Fruit',
  bills: 'Bills',
  submit: 'SUBMIT',
  income: 'Income',
  rental: 'Rental',
  health: 'Health',
  salary: 'Salary',
  signIn: 'Sign In',
  notNow: 'Not now',
  balance: 'Balance',
  coupons: 'Coupons',
  lottery: 'Lottery',
  shopping: 'Shopping',
  expenses: 'Expenses',
  clothing: 'Clothing',
  settings: 'Settings',
  vegetable: 'Vegetable',
  insurance: 'Insurance',
  education: 'Education',
  ratingUs: 'Rating Us!',
  moneyManager: 'Money Manager',
  entertainment: 'Entertainment',
  onBoardingTitle3: 'Cloud Backup',
  googleLogin: 'Sign in with Google',
  onBoardingTitle2: 'Intuitive Graph',
  facebookLogin: 'Log in with Facebook',
  categorySettings: 'Category Settings',
  onBoardingTitle1: 'One-click Tracking',
  onBoardingDesc2: 'Know where your money goes',
  onBoardingDesc3: 'Sign in to support cloud sync and backup',
  ratingDesc: 'Your support will help us\nto improve the app.',
  fBPlaceHolder: 'Give your feedback here..!!',
  onBoardingDesc1: 'Track your financial activity just a few seconds',
  warnText: 'Please log in as soon as  possible to avoid losing data',
  feedbackDesc:
    'Your feedback is highly appreciated and will help us\nto improve.',
};
