export const string = {
  onBoardingTitle1: 'One-click Tracking',
  onBoardingTitle2: 'Intuitive Graph',
  onBoardingTitle3: 'Cloud Backup',
  onBoardingDesc1: 'Track your financial activity just a few seconds',
  warnText: 'Please log in as soon as  possible to avoid losing data',
  onBoardingDesc2: 'Know where your money goes',
  onBoardingDesc3: 'Sign in to support cloud sync and backup',
  skip: 'skip',
  signIn: 'Sign In',
  notNow: 'Not now',
  moneyManager: 'Money Manager',
  facebookLogin: 'Log in with Facebook',
  googleLogin: 'Sign in with Google',
  income: 'Income',
  expenses: 'Expenses',
  balance: 'Balance',
  bills: 'Bills',
  book: 'Book',
  car: 'Car',
  clothing: 'Clothing',
  education: 'Education',
  entertainment: 'Entertainment',
  food: 'Food',
  fruit: 'Fruit',
  gift: 'Gift',
  health: 'Health',
  home: 'Home',
  insurance: 'Insurance',
  shopping: 'Shopping',
  vegetable: 'Vegetable',
  coupons: 'Coupons',
  lottery: 'Lottery',
  rental: 'Rental',
  salary: 'Salary',
  sale: 'Sale',
  fun: 'Fun',
};
